name: Studor Testing with Jest

on:
  pull_request: 
  workflow_dispatch: 
  push:
    branches: [testing, main]

jobs:
  unit-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm test